### ISSUE TITLE
rlc_test failed when using the rlcCircuitBuilder

### ISSUE THREAD

**Issue by UsedToBe97** [axiom-crypto/axiom-eth#12]
When I tried to run the following command in axiom-eth: community version I got an error, does anybody know why?

Here is the command line for reproduction: (in community-edition branch)

cargo test --package axiom-eth --lib -- rlp::tests::rlc::test_rlc --exact --nocapture

The error is following:

![telegram-cloud-photo-size-5-6122711958076636998-y](https://github.com/axiom-crypto/axiom-eth/assets/33629224/cd0d3af4-ba0c-4509-a5cf-39d8c63dacd5)

**Comment by jonathanpwang** [comment]
Fixed in https://github.com/axiom-crypto/axiom-eth/pull/11
