### ISSUE TITLE
Build errors 

### ISSUE THREAD

**Issue by ltfschoen** [axiom-crypto/axiom-eth#21]
To build this repo it uses an old rust-toolchain https://github.com/axiom-crypto/axiom-eth/blob/main/rust-toolchain#L1 'nightly-2022-10-28', so when you run `cargo build` it gives errors for some dependencies since it's using rustc 1.66 but the dependencies require 1.70. 

so the following worked for me (instead of running `cargo update`). just choosing dependencies like an older version of clap that didn't require 1.70 shown here https://crates.io/crates/clap/versions
```bash
cargo update -p anstyle@1.0.3 --precise 1.0.2
cargo update -p clap@4.4.5 --precise 4.3.24
cargo update -p clap_lex@0.5.1 --precise 0.5.0
cargo build --verbose
cargo run --bin header_chain --release -- --help
```

**Comment by norbubb** [comment]
`cargo update -p anstyle-parse@0.2.2 --precise 0.2.0`

**Comment by enricobottazzi** [comment]
Same issue was encountered here. Confirm that the solution proposed by @ltfschoen + @norbubb works
```bash
cargo update -p anstyle-parse@0.2.2 --precise 0.2.0
cargo update -p clap@4.4.6 --precise 4.3.24
cargo update -p clap_lex@0.5.1 --precise 0.5.0
cargo update -p anstyle@1.0.4 --precise 1.0.2
```

**Comment by jonathanpwang** [comment]
This should be fixed in https://github.com/axiom-crypto/axiom-eth/commit/014a2d059e48f8f4ad83a7650f1d0bf9a69a056a
